### ISSUE TITLE
for pom.csv 

### ISSUE THREAD

**Issue by apoorvacha** [apoorvacha/ASE_Project#3]
Traceback (most recent call last):
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 61, in <module>
    main()
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 55, in main
    run_tests(src) 
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 42, in run_tests
    if(test(src)):
  File "/Users/apoorva/Documents/ASE_Project/source/Examples.py", line 190, in test_bins
    for k,t in enumerate(Discretization.bins(data.cols.x, {"best": best.rows, "rest": rest.rows})):
  File "/Users/apoorva/Documents/ASE_Project/source/Discretization.py", line 43, in bins
    out.append(n_ranges_list if hasattr(col, "isSym") and col.isSym else mergeAny(n_ranges))
  File "/Users/apoorva/Documents/ASE_Project/source/Discretization.py", line 84, in mergeAny
    return noGaps(ranges0) if (len(ranges1)==len(ranges0)) else mergeAny(ranges1)
  File "/Users/apoorva/Documents/ASE_Project/source/Discretization.py", line 66, in noGaps
    t[-1].hi = max
KeyError: -1

**Comment by vasuagrawal19** [comment]
Issue fixed. t was coming in as empty. Added checks to handle the issue.
