### ISSUE TITLE
nasa93dem.csv, SSM , hc120011.csv, hc12001.csv

### ISSUE THREAD

**Issue by apoorvacha** [apoorvacha/ASE_Project#4]
Traceback (most recent call last):
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 61, in <module>
    main()
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 55, in main
    run_tests(src) 
  File "/Users/apoorva/Documents/ASE_Project/source/Start.py", line 42, in run_tests
    if(test(src)):
  File "/Users/apoorva/Documents/ASE_Project/source/Examples.py", line 205, in test_explain
    rule, most= Discretization.xpln(data,best,rest)
  File "/Users/apoorva/Documents/ASE_Project/source/Discretization.py", line 123, in xpln
    maxSizes[ranges[0].txt] = len(ranges)
IndexError: list index out of range

**Comment by vasuagrawal19** [comment]
ranges were coming empty. Added checks to handle the issue.
